node:
  id: id_1
  cluster: test
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 1935
static_resources:
  clusters:
  - name: xds_server
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: xds_server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 50051
dynamic_resources:
  cds_config:
    path: "./cds.conf"
  lds_config:
    path: "./lds.conf"
#  ads_config:
#    api_type: "DELTA_GRPC"
#    transport_api_version: "V3"
#    grpc_services:
#      envoy_grpc: 
#        cluster_name: xds_server 
