cc_binary(
    name = "build_sanity",
    srcs = [
        "build_sanity.c",
    ],
    deps = [
        "@openssl//:ssl",
        "@openssl//:crypto",
        "@nitrox_driver//:nitrox",
    ],
    visibility = ["//visibility:public"],
)
