FROM envoyproxy/envoy-dev:latest
#FROM envoyproxy/envoy-dev:3504d40f752eb5c20bc2883053547717bcb92fd8

RUN apt-get update && apt-get -q install -y \
    curl iproute2 net-tools vim iputils-ping redis-server
#CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
CMD tail -f /dev/null
