# The xDS/ADS server loads this configuration and serve it to Envoy

name: listener1
address:
  socket_address:
    address: 0.0.0.0
    port_value: 80
access_log:
- name: envoy.access_loggers.file
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
    path: "/tmp/listener_access.log"
filter_chains:
- filters:
  - name: envoy.filters.network.http_connection_manager
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: ingress_http
      rds:
        config_source:
          path: "/etc/rds_http.yaml"
        route_config_name: local_http_route 
      http_filters:
      - name: envoy.filters.http.on_demand
        typed_config: {}
      - name: envoy.filters.http.router
        typed_config: {}
